# Continuous integration (CI) triggers cause a pipeline to run whenever you push
# an update to the specified branches or you push specified tags.
trigger:
  batch: true
  tags:
    include:
      - sotepe-efecte-iloq-v*

# Pull request (PR) triggers cause a pipeline to run whenever a pull request is
# opened with one of the specified target branches, or when updates are made to
# such a pull request.
#
# GitHub creates a new ref when a pull request is created. The ref points to a
# merge commit, which is the merged code between the source and target branches
# of the pull request.
#
# Opt out of pull request validation
pr: none

# By default, use self-hosted agents
pool: Default

resources:
  repositories:
    # Azure DevOps repository
    - repository: sotepe-efecte-iloq-pipelines
      type: git
      # Azure DevOps project/repository
      name: sotepe-efecte-iloq/sotepe-efecte-iloq-pipelines

extends:
  # Filename in Azure DevOps Repository
  template: components/sotepe-efecte-iloq/pipelines/sotepe-efecte-iloq-production.yml@sotepe-efecte-iloq-pipelines
  # parameters:
    # Application build arguments and config map values as key value pairs.
    # Does not contain all buildArguments or configMap values, the rest located in sotepe-efecte-iloq-pipelines
    # The values here will override the values defined in the sotepe-efecte-iloq-pipelines repository
    # buildArgs:
    #   DEBUG: 1
    # configMap: # pod environment variables
    #   DEBUG: 1
